In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.feature_selection import r_regression
from sklearn.metrics import classification_report

In [2]:
data = pd.read_excel('/home/jovyan/Project_Folder/Dry_Bean_Dataset.xlsx')

In [3]:
data = data.dropna()
data = data.drop_duplicates()

In [4]:
#target_mapping = {cls: idx for idx, cls in enumerate(data['Class'].unique())}
#data['Class'] = data['Class'].map(target_mapping)

In [5]:
#here i split my data into training and test data
X = data.drop('Class', axis=1)
y= data['Class']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [7]:
#print("Training set size:", X_train.shape)
#print("Testing set size:", X_test.shape) 

In [8]:
# Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Creating and fitting the Logistic Regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, multi_class='multinomial')

In [9]:
y_pred = model.predict(X_test_scaled)

In [10]:
# Evaluating the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred)) 

Confusion Matrix:
 [[360   0  22   0   0   3  11]
 [  0 161   0   0   0   0   0]
 [ 18   0 440   0   6   2   7]
 [  0   0   0 972   0  14  79]
 [  0   0   7   5 529   0  12]
 [  7   0   0   9   0 583  19]
 [  1   0   1  63  19  14 699]]
Accuracy: 0.9214865862663056
              precision    recall  f1-score   support

    BARBUNYA       0.93      0.91      0.92       396
      BOMBAY       1.00      1.00      1.00       161
        CALI       0.94      0.93      0.93       473
    DERMASON       0.93      0.91      0.92      1065
       HOROZ       0.95      0.96      0.96       553
       SEKER       0.95      0.94      0.94       618
        SIRA       0.85      0.88      0.86       797

    accuracy                           0.92      4063
   macro avg       0.93      0.93      0.93      4063
weighted avg       0.92      0.92      0.92      4063

